openapi: 3.0.0
info:
    description: "API do projeto."
    version: "1.0.0"
    title: "API clínica"

servers:
    - url: http://localhost:3000
      description: Servidor local.

tags:
    - name: "Orders"
      description: "Inserção, edição e consultas de pedidos de exames"

paths:
    /orders:
        get:
            tags:
                - "Orders"
            summary: "Lista os exames ativos."
            operationId: "listOrders"
            parameters:
                - in: query
                  name: patient_id
                  schema:
                      type: number
                - in: query
                  name: exam_type
                  schema:
                      type: string
                - in: query
                  name: status
                  schema:
                      type: string
            responses:
                200:
                    $ref: "#/components/responses/ListOrders"
                400:
                    $ref: "#/components/responses/BadRequest"
                500:
                    $ref: "#/components/responses/InternalError"
        post:
            tags:
                - "Orders"
            summary: "Cria um pedido de exame."
            operationId: "createOrders"
            parameters:
                - in: path
                  name: order
                  required: true
                  schema:
                      type: object
                      properties:
                          patient_id:
                              type: number
                          exam_type:
                              type: string
                          date:
                              type: string
            responses:
                201:
                    $ref: "#/components/responses/Order"
                400:
                    $ref: "#/components/responses/BadRequest"
                500:
                    $ref: "#/components/responses/InternalError"

components:
    responses:
        Order:
            description: "Pedido de exame."
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/order"
        ListOrders:
            description: "Listagem de pedidos de exames."
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: object
                            properties:
                            $ref: "#/components/schemas/order"
        Success:
            description: "Requisição efetuada com sucesso."
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/success"
        NotFound:
            description: "Recurso fornecido não encontrado"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error_response"
        BadRequest:
            description: "Erro no processamento da requisição, dados fornecidos invalidos"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error_response"
        InternalError:
            description: "Internal server error. Consulte o campo error_description para maiores detalhes."
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error_response"
        Unauthorized:
            description: "Falha na autenticação"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error_response"
        Conflict:
            description: "Falha ao persistir dados na base de dados"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error_response"
        Forbidden:
            description: "Permissões insuficientes"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error_response"
    schemas:
        error_response:
            type: object
            properties:
                error_description:
                    type: string
                error:
                    type: string
        success:
            type: object
            properties:
                message:
                    type: string
        order:
            type: object
            properties:
                _id:
                    type: string
                patient_id:
                    type: number
                exam_type:
                    type: string
                status:
                    type: string
                __v:
                    type: number
